"""
tools/train_anpr.py — ANPR Model Fine-Tuning Script
=====================================================
Fine-tunes YOLOv11n on an Indian Licence Plate dataset and exports the
trained model to ONNX so it can be used directly by ANPRDetector.

Dataset
-------
Option A — IIT Roorkee ANPR Dataset:
  Contact authors at IIT Roorkee (public release).
  Place images in  : data/anpr_dataset/images/
  Place labels in  : data/anpr_dataset/labels/   (YOLO format .txt)

Option B — Kaggle "Indian Number Plates Detection":
  kaggle datasets download -d tustunkog/indian-number-plates-detection
  unzip the archive, then:
    mv images/ data/anpr_dataset/images/
    mv labels/ data/anpr_dataset/labels/

Both datasets use YOLO annotation format (class cx cy w h normalised 0-1).
There is typically only ONE class: 0 = licence_plate.

Usage
-----
  pip install ultralytics pyyaml
  python tools/train_anpr.py [--epochs 50] [--imgsz 640] [--batch 16]

The script will:
  1. Create data/anpr_dataset/dataset.yaml automatically.
  2. Fine-tune YOLOv11n (downloaded from Ultralytics hub if not present).
  3. Export best.pt → models/anpr_plate_detect.onnx.

After training, update cameras.yaml:
  settings.anpr.model: "models/anpr_plate_detect.onnx"
"""

import argparse
import os
import pathlib
import sys
import textwrap

# ── Ensure project root is on PYTHONPATH ────────────────────────────────────
_PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_PROJECT_ROOT))


def _write_dataset_yaml(dataset_dir: pathlib.Path) -> pathlib.Path:
    """
    Create the YOLO dataset YAML if it doesn't already exist.
    Assumes the dataset has:
      images/train/    (or images/ for auto-split)
      labels/train/
    """
    yaml_path = dataset_dir / "dataset.yaml"

    # Determine train/val split directories
    img_dir = dataset_dir / "images"
    train_dir = img_dir / "train"
    val_dir   = img_dir / "val"

    if train_dir.exists():
        train_path = str(train_dir)
        val_path   = str(val_dir) if val_dir.exists() else str(train_dir)
    else:
        # Flat structure — Ultralytics will auto-split
        train_path = str(img_dir)
        val_path   = str(img_dir)

    content = textwrap.dedent(f"""\
        # IBVAP — Indian ANPR Dataset Configuration (auto-generated by train_anpr.py)
        path: {dataset_dir.resolve()}
        train: {train_path}
        val:   {val_path}

        # Classes
        nc: 1
        names:
          0: licence_plate
    """)

    yaml_path.write_text(content)
    print(f"[train_anpr] Dataset YAML written to: {yaml_path}")
    return yaml_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fine-tune YOLOv11n for Indian ANPR and export to ONNX."
    )
    parser.add_argument("--epochs",    type=int,   default=50,    help="Training epochs (default: 50)")
    parser.add_argument("--imgsz",     type=int,   default=640,   help="Input image size (default: 640)")
    parser.add_argument("--batch",     type=int,   default=16,    help="Batch size (default: 16; reduce if OOM)")
    parser.add_argument("--device",    type=str,   default="0",   help="CUDA device index or 'cpu' (default: 0)")
    parser.add_argument("--data-dir",  type=str,   default="data/anpr_dataset", help="Dataset root dir")
    parser.add_argument("--model",     type=str,   default="yolo11n.pt",        help="Base model checkpoint")
    parser.add_argument("--project",   type=str,   default="runs/anpr",         help="Training output dir")
    parser.add_argument("--name",      type=str,   default="exp",               help="Experiment name")
    parser.add_argument("--export-only", action="store_true",
                        help="Skip training, export existing best.pt to ONNX only")
    args = parser.parse_args()

    # ── Import Ultralytics ────────────────────────────────────────────────────
    try:
        from ultralytics import YOLO
    except ImportError:
        print("[train_anpr] ERROR: ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)

    # ── Dataset directory check ───────────────────────────────────────────────
    dataset_dir = _PROJECT_ROOT / args.data_dir
    images_dir  = dataset_dir / "images"

    if not images_dir.exists():
        print(textwrap.dedent(f"""
        [train_anpr] ERROR: Dataset images directory not found: {images_dir}

        Please download the dataset first:

          Option A — Kaggle (recommended):
            pip install kaggle
            kaggle datasets download -d tustunkog/indian-number-plates-detection
            Expand the ZIP, then:
              mkdir -p data/anpr_dataset/images data/anpr_dataset/labels
              mv <extracted>/images/* data/anpr_dataset/images/
              mv <extracted>/labels/* data/anpr_dataset/labels/

          Option B — Manual:
            Place images in : data/anpr_dataset/images/
            Place labels in : data/anpr_dataset/labels/   (YOLO .txt format)

        Then re-run: python tools/train_anpr.py
        """))
        sys.exit(1)

    # ── Create dataset YAML ───────────────────────────────────────────────────
    dataset_yaml = _write_dataset_yaml(dataset_dir)

    # ── Output ONNX path ──────────────────────────────────────────────────────
    onnx_out = _PROJECT_ROOT / "models" / "anpr_plate_detect.onnx"
    os.makedirs(onnx_out.parent, exist_ok=True)

    if args.export_only:
        # Find the most recent best.pt in runs/anpr/
        runs_dir = _PROJECT_ROOT / args.project
        best_pt_candidates = sorted(
            runs_dir.rglob("best.pt"), key=lambda p: p.stat().st_mtime, reverse=True
        )
        if not best_pt_candidates:
            print(f"[train_anpr] ERROR: No best.pt found in {runs_dir}. Run training first.")
            sys.exit(1)
        best_pt = best_pt_candidates[0]
        print(f"[train_anpr] Export-only mode. Using: {best_pt}")
        model = YOLO(str(best_pt))
    else:
        # ── Training ─────────────────────────────────────────────────────────
        print(f"[train_anpr] Loading base model: {args.model}")
        model = YOLO(args.model)   # downloads from hub if not present

        print(f"[train_anpr] Starting training: {args.epochs} epochs, "
              f"imgsz={args.imgsz}, batch={args.batch}, device={args.device}")

        results = model.train(
            data=str(dataset_yaml),
            epochs=args.epochs,
            imgsz=args.imgsz,
            batch=args.batch,
            device=args.device,
            project=str(_PROJECT_ROOT / args.project),
            name=args.name,
            exist_ok=True,
            # Augmentation settings tuned for Indian LP (tight crops, varied lighting)
            hsv_h=0.015,
            hsv_s=0.5,
            hsv_v=0.4,
            degrees=5.0,
            translate=0.1,
            scale=0.4,
            shear=2.0,
            perspective=0.0002,
            flipud=0.0,
            fliplr=0.0,    # plates should not be mirrored
            mosaic=0.8,
        )
        print(f"[train_anpr] Training complete. Best checkpoint: {results.save_dir}/weights/best.pt")
        best_pt = pathlib.Path(results.save_dir) / "weights" / "best.pt"
        model = YOLO(str(best_pt))

    # ── Export to ONNX ────────────────────────────────────────────────────────
    print(f"[train_anpr] Exporting to ONNX: {onnx_out}")
    model.export(
        format="onnx",
        imgsz=args.imgsz,
        simplify=True,
        dynamic=False,         # fixed batch=1 for ONNX Runtime
        opset=17,
    )

    # Ultralytics places the ONNX next to the .pt; move it to models/
    exported_onnx = best_pt.parent / (best_pt.stem + ".onnx")
    if not exported_onnx.exists():
        # Fallback: sometimes named after the model
        exported_onnx = best_pt.with_suffix(".onnx")

    if exported_onnx.exists():
        import shutil
        shutil.copy2(str(exported_onnx), str(onnx_out))
        print(f"[train_anpr] ✓ ONNX model copied to: {onnx_out}")
    else:
        print(f"[train_anpr] WARNING: Could not find exported ONNX at {exported_onnx}.")
        print(f"             Look in the training output dir and copy manually to: {onnx_out}")

    print(textwrap.dedent(f"""
    ════════════════════════════════════════════
     ANPR Model Ready
    ════════════════════════════════════════════
     ONNX path  : {onnx_out}
     cameras.yaml setting:
       settings:
         anpr:
           model: "models/anpr_plate_detect.onnx"
    ════════════════════════════════════════════
    """))


if __name__ == "__main__":
    main()
